# LETTERPOOL LOCAL
GET http://localhost:3000/api/letterpool/daily
Content-Type: application/json

### 
GET http://localhost:3000/api/letterpool/words
Content-Type: application/json


### LETTERPOOL DEPLOYED
GET https://scrabbleapi.onrender.com/api/letterpool/daily


